### ISSUE TITLE
Configurable width/height for each chart

### ISSUE THREAD

**Issue by stufro** [stufro/obsidian-hill-charts#3]
Make it possible to override the chart width and height in the input yml. e.g.

```yml
points:
  - position: 50
    text: Foo
width: 500
height: 300
```
